### ISSUE TITLE
ClassCastException on some notifications

### ISSUE THREAD

**Issue by Kurtpenter** [holylobster/nuntius-android#29]
When taking a screenshot of the app:

03-19 23:02:25.406   3498-18338/org.holylobster.nuntius E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-126378
    Process: org.holylobster.nuntius, PID: 3498
    java.lang.ClassCastException: android.graphics.drawable.VectorDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
            at org.holylobster.nuntius.Message.toJSON(Message.java:91)
            at org.holylobster.nuntius.Message.toJSON(Message.java:62)
            at org.holylobster.nuntius.Connection$1.run(Connection.java:51)

**Comment by Kurtpenter** [comment]
Fixed by 17f708896a2528ea5999fbab64b51c2b31b6f7ef
